
name: ramal_e_haq
description: Ramal system app in Roman Urdu for Android
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
